version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: apps/web/Dockerfile
        ports: 
            - 3000:3000
        depends_on:
            - socket
    socket: 
        build:
            context: .
            dockerfile: apps/socket/Dockerfile
        ports: 
            - 4000:4000